-- Add preview_html column to discovered_components
-- Stores a self-contained HTML/CSS visual representation of the component
-- Generated by AI during analysis, rendered directly in the app (no sandbox needed)
alter table public.discovered_components add column preview_html text;
